# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-11 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=32)),
                ('add_time', models.CharField(max_length=32)),
            ],
        ),
    ]
