# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-11 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialno', '0002_auto_20190311_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialno',
            name='is_used',
            field=models.BooleanField(default=0),
        ),
    ]
