# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialno', '0003_serialno_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialno',
            name='is_used',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=0),
        ),
    ]
