# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wechat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatPush',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('push_time', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat_app.Chatroom')),
            ],
            options={
                'db_table': 'wecaht_wechat_push',
            },
        ),
    ]
