# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-11 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('level', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], default=3)),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 20, 6, 41343))),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('mark', models.BooleanField(default=1)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'bs_system_role',
            },
        ),
        migrations.CreateModel(
            name='RoleAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.BooleanField(default=1)),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 20, 6, 42335))),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Auth')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
            ],
            options={
                'db_table': 'bs_system_role_auth',
            },
        ),
    ]
