# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=120, unique=True)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('remark', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'wecaht_chatroom_chatroom',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, '文字'), (2, '图片'), (3, '文件')])),
            ],
            options={
                'db_table': 'wechat_reply',
            },
        ),
        migrations.CreateModel(
            name='ReplyToChatroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField(null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('filepath', models.FileField(null=True, upload_to='uploadfile/')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat_app.Chatroom')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat_app.Reply')),
            ],
            options={
                'db_table': 'wechat_reply_to_chatroom',
            },
        ),
        migrations.AlterUniqueTogether(
            name='replytochatroom',
            unique_together=set([('chatroom', 'reply')]),
        ),
    ]
