# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-11 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManage', '0003_auto_20190311_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 52, 35, 99366)),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 52, 35, 102837)),
        ),
    ]
