# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-04 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManage', '0005_auto_20190311_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 15, 53, 19, 269799)),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 15, 53, 19, 271782)),
        ),
    ]
